points_per_side: 32 # default: 32
points_per_batch: 64  # default: 64
pred_iou_thresh: 0.84  # default: 0.88
stability_score_thresh: 0.95 # default: 0.95
stability_score_offset: 1.0 # default: 1.0
box_nms_thresh: 0.7 # default: 0.7
crop_n_layers: 1 # default: 0
crop_nms_thresh: 0.9 # default: 0.7
# crop_overlap_ratio: 0.5 # default: None
crop_n_points_downscale_factor: 1 # default: 1
min_mask_region_area: 80 # default: 0
